### DISCUSSION TITLE
Support FormData requests

### DISCUSSION THREAD

**Discussion by cobbweb** [LucasPickering/slumber#235] [Ideas]
Would be neat to support FormData requests in a similar fashion to curl. I guess for the `body:` you could use a `!formdata` tag?

```yaml
requests:
  upload_fish_image: !request
        method: POST
        url: "{{host}}/fishes"
        body: !formdata
          fish_id: "cod"
          fish_image: "@./cod_photo.jpg"
```

Not sure how viable this approach is, just wanted to get the conversation started :)

**Comment by LucasPickering** [comment]
I like this idea, a couple thoughts on your example:

- Correct me if I'm wrong, but I believe the `@` syntax is specific to curl, and I assume you just pulled that in as an example. I would want to leverage the template/chain system for this, rather than introduce new syntax
- I'd like to lean on the `Content-Type` header rather than adding a tag to the `body` field. You'll need to submit `Content-Type` anyway to tell the server what you're sending.

With those in mind, here's what I'm thinking:

```yaml
chains:
  cod_image: !file
    path: ./cod_photo.jpg
requests:
  upload_fish_image: !request
    method: POST
    url: "{{host}}/fishes"
    headers:
      Content-Type: multipart/form-data
    body:
      fish_id: "cod"
      fish_image: "{{chains.cod_image}}"
```

The changes I see immediately here that are needed to support this:

1. Binary templates. Right now templates have to resolve to strings. I believe we could update them to resolve to any arbitrary bytes without *too* much trouble, but I'd have to start poking around with that to be sure
2. `body` would have to support map values (right now it just supports strings)
3. We would need an additional adapter layer that uses the `Content-Type` header to map the structured body into bytes for the HTTP request. 
  - This would actually be useful beyond forms, because you could then use structured bodies for other content types, e.g. passing a map for `application/x-www-form-urlencoded` 
4. This is specific to `multipart/form-data`, but we would need to add [boundary](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#boundary) values to the `Content-Type` header. Fortunately reqwest (the HTTP library that Slumber uses) [will handle this for us](https://docs.rs/reqwest/latest/reqwest/struct.RequestBuilder.html#method.multipart).

In terms of difficulty/level of effort, I would rank these (most to least) as: 3, 4, 1, 2. It all seems pretty feasible to me though. Does this sound like it would solve your problem? If so I can write out some issues for this and get started on it.
