### ISSUE TITLE
Prompt is always rendered as sensitive

### ISSUE THREAD

**Issue by snaggen** [LucasPickering/slumber#108]
I have the following chain defined:
```yaml
chains:
  user:
    source: !prompt Enter User
    sensitive: false
```
But the prompt I get doesn't let me see the input.
