### ISSUE TITLE
Add more convenient way to set authorization

### ISSUE THREAD

**Issue by snaggen** [LucasPickering/slumber#110]
I don't know if there is any support for Basic Auth, couldn't find it in the docs. If not, it would be nice to have. Currently I just set the header Authorization: Basic ... , but I think it would be nice to be able to set the username and password instead.

**Comment by LucasPickering** [comment]
I like this idea. I think the best design would be adding a new field to the [Recipe](https://slumber.lucaspickering.me/book/api/request_recipe.html) type called `authorization`, which has multiple variants. This would override the `Authorization` header. Some examples:

```yaml
get_user:
  name: Get User
  method: GET
  url: "{{host}}/anything/{{user_guid}}"
  authorization: !basic
    username: "{{username}}"
    password: "{{password}}"

get_user:
  name: Get User
  method: GET
  url: "{{host}}/anything/{{user_guid}}"
  authorization: !bearer
    token: "{{token}}"
```
