### ISSUE TITLE
Prompt occurs multiple times if re-used in request

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#118]
If the same chained prompt value is used multiple times in a request, it prompts once per usage. It should only prompt once per request.

```yaml

chains:
  username:
    source: !command ["sh", "-c", "whoami | tr -d '\n'"]
  password:
    source: !prompt Password
    sensitive: true

requests:
  login:
    method: POST
    url: "{{host}}/anything/login"
    query:
      sudo: yes_please
      password: "{{chains.password}}"
    body: |
      {
        "username": "{{username}}",
        "password": "{{chains.password}}"
      }
```

This is a tough one to fix because each template render is executed independently and in parallel during request build. The solution would probably be to scan all parsed templates at the start of the request, and collect all used chains into a de-duplicated pool. Then resolve those chain values _first_, before finally rendering the templates themselves. This has the added benefit of de-duplicating other chain types too (e.g. if a slow shell command is chained, it won't have to execute multiple times).

It's very possible, just requires rearchitecting the template code a fair amount.

[futures::future::shared](https://docs.rs/futures/latest/futures/future/trait.FutureExt.html#method.shared) may be helpful for caching the futures.
