### ISSUE TITLE
Recursive templating?

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#15]
Would recursive templating be helpful? It would be a pain to implement but it's possible so I want to make sure there's demand before I do it. It would enable cases like this:

```yaml
profiles:
  - id: foo
    data:
      token: Bearer {{chains.token}}

chains:
  - id: token
    source: !file ./token.txt
```
