### ISSUE TITLE
Switch from JSONPath to jq?

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#158]
It's worthwhile investigating switching from JSONPath to JQ for selectors. JQ is much more powerful and also better documented.

**Comment by LucasPickering** [comment]
After thinking about this a bit, I want to stick with JSONPath. It's simpler and will be familiar to people coming from Insomnia. After #151, `jq` will be usable anyway by piping through a `!command` chain, e.g.:

```yaml
chains:
  fishes:
    source: !request
      recipe: fishes
  fish:
    source: !command
      command: ["sh", "-c", "echo {{chains.fishes}} | jq .[0]"]
```
