### ISSUE TITLE
Escape quotes in template values

### ISSUE THREAD

**Issue by Aloso** [LucasPickering/slumber#189]
**Is your feature request related to a problem? Please describe.**
I want to insert a file into a JSON field:

```yml
chains:
  email-body:
    source: !file
      path: ./email-body.html

requests:
  send-email: !request
    method: POST
    url: '{{host}}/v1/outbox'
    headers:
      Content-Type: application/json
    body: |
      {
        "type": "HTML",
        "content": "{{chains.email-body}}"
      }
```

This doesn't work, because the email body contains line breaks and double quotes that need to be escaped in the resulting JSON.

**Describe the solution you'd like**
Add a template syntax for escaping strings:
```
{
  "type": "HTML",
  "content": {{chains.email-body | to-json}}
}
```

**Alternative 1**
Add an option to the chain:
```yml
chains:
  email-body:
    source: !file
      path: ./email-body.html
    format: json
```

**Alternative 2**
We know that the body is JSON because of the `Content-Type` header, so we can escape values in the body automatically, if they are in double quotes:

```yml
requests:
  foo: !request
    headers:
      Content-Type: application/json
    body: |
      {
        "lorem": "{{this-is-escaped}}",
        "ipsum": {{this-is-not-escaped}}
      }
  bar: !request
    # no Content-Type specified!
    body: |
      {
        "lorem": "{{not-escaped}}",
        "ipsum": {{not-escaped}}
      }
```

**Comment by LucasPickering** [comment]
This is achieveable already using `jq`:

```yaml
chains:
  email-body:
    source: !command
      command: [jq, -R, -s, ".", ./email-body.txt]

requests:
  send-email: !request
    method: POST
    url: "{{host}}/v1/outbox"
    headers:
      Content-Type: application/json
    body: |
      {
        "type": "HTML",
        "content": {{chains.email-body}}
      }
```

The contents of `email-body.txt` is:

```
"Hello!" That is what I say
```

This results in this request body:

```json
{
  "type": "HTML",
  "content": "\"Hello!\" That is what I say\n"

}
```

## From another request

If you want to escape JSON from another request rather than a file, you can use [nested chains](https://slumber.lucaspickering.me/book/user_guide/chains.html#chaining-chains):

```yaml
chains:
  email-body:
    source: !request
      recipe: get-email
    selector: $.headers
  email-body-escaped:
    source: !command
      command: [sh, -c, "echo '{{chains.email-body}}' | jq -R -s '.'"]

requests:
  get-email: !request
    method: GET
    url: "https://httpbin.org/anything/v1/outbox"

  send-email: !request
    method: POST
    url: "https://httpbin.org/anything/v1/outbox"
    headers:
      Content-Type: application/json
    body: |
      {
        "type": "HTML",
        "content": {{chains.email-body-escaped}}
      }
```

## Conclusion

In general I'd like to lean on `!command` (and `jq` in particular) as much as possible for stuff like this. It's a bit less user friendly but it's way more flexible. There's no way we'll be able to implement everything users might need in terms of data processing, so I'd rather just outsource it all.

I'm going to close this, but if this doesn't cover your use case you can reopen it.
