### ISSUE TITLE
Add `stdin` option to command chains

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#190]
**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

Right now, it's tedious to write command chains that require stdin input. For example:

```yaml
chains:
  email-body:
    source: !request
      recipe: get-email
    selector: $.headers
  email-body-escaped:
    source: !command
      command: [sh, -c, "echo '{{chains.email-body}}' | jq -R -s '.'"]
```

The goal here is to reduce the number of use cases where users have to invoke the shell, without too much effort (see #153 for another example). This has two benefits:
- More user friendly
- Reduce cross-platform issues

**Describe the solution you'd like**
_A clear and concise description of what you want to happen_

A new field `stdin` on the `!command` variant:

```yaml
chains:
  email-body:
    source: !request
      recipe: get-email
    selector: $.headers
  email-body-escaped:
    source: !command
      command: [jq, -R, -s, '.']
      stdin: "{{chains.email-body}}"
```

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered_

The primary alternative is doing nothing, since this is already possible by invoking the shell directly.

**Additional context**
_Add any other context or screenshots about the feature request here_

If anyone wants to implement this, the work involved is:
- Add `stdin` field (type `Template`) to [ChainSource::Command](https://github.com/LucasPickering/slumber/blob/5b164ac515ed37a78707df2e567299915ad90bc9/src/collection/models.rs#L210)
- Add logic to render the `stdin` value, then pipe that to the subprocess in [render.rs](https://github.com/LucasPickering/slumber/blob/5b164ac515ed37a78707df2e567299915ad90bc9/src/template/render.rs#L438)
- Add tests in [template.rs](https://github.com/LucasPickering/slumber/blob/5b164ac515ed37a78707df2e567299915ad90bc9/src/template.rs#L562)
- Add docs in [chain_source.md](https://raw.githubusercontent.com/LucasPickering/slumber/master/docs/src/api/request_collection/chain_source.md)
