### ISSUE TITLE
Duplicate keys when typing in prompt in Windows Terminal

### ISSUE THREAD

**Issue by jamal** [LucasPickering/slumber#226]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?** yes

**Describe the bug**
In Windows Terminal, typing in the prompt dialog enters multiple keys per keypress making it difficult to use the prompt. Tested using PowerShell, Bash (cygwin), and Nushell. Pasting is also a problem and enters more than one key per character.

**To Reproduce**
_Steps to reproduce the behavior_
1. Run Slumber in Windows Terminal
2. Select a request that uses a prompt chain
3. Press enter
4. Type a key and notice that it is entered multiple times

**Expected behavior**
A key should be entered once.

**Screenshots**
![image](https://github.com/LucasPickering/slumber/assets/58573/3aa4017f-01b7-4169-8578-1dd4db96df9a)
In this screenshot, I typed `a` once, and then `b`, and then `c` (the `S` is from Win+Shift+S to take a screenshot 😅 )

**Version (please complete the following information):**

- OS: Windows 10 - 22H2 (Build 19045.4412)
- Terminal: Windows Terminal 1.19.11213.0
- Slumber Version: 1.3.0

**Additional context**:

Request collection:
```yaml
chains:
  authorization_code:
    source: !prompt
      message: Authorization Code

requests:
  login: !request
    method: POST
    url: "https://www.example.com"
    headers:
      Accept: application/json
      Content-Type: application/x-www-form-urlencoded
    # authentication: !basic
    #   username: "{{client_id}}"
    #   password: "{{client_secret}}"
    body: |
      grant_type=authorization_code&code={{chains.authorization_code}}
```
