### ISSUE TITLE
New line in yml is not stripped from request body

### ISSUE THREAD

**Issue by jamal** [LucasPickering/slumber#228]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?** Yes

**Describe the bug**
New line is not being stripped from the request body, causing an erroneous `0a` to be included in the request. For example, an OAuth POST request:
```
00000000  67 72 61 6e 74 5f 74 79 70 65 3d 61 75 74 68 6f   grant_type=autho
00000010  72 69 7a 61 74 69 6f 6e 5f 63 6f 64 65 26 63 6f   rization_code&co
00000020  64 65 3d 66 6f 6f 0a                              de=foo          
```

The `0a` can be an issue if the called service is not stripping white spaces from the input as well.

If the `body` is the last statement in the yml, with no new line this is issue is not present.

**To Reproduce**
_Steps to reproduce the behavior_
1. Create a slumber.yml with a request body, but make sure there is a new line at the end of the request
2. Make the request through Slumber
3. If you debug the request body, you'll see that the new-line was included in the body

Example yaml:
```

  example: !request
    method: POST
    url: "http://www.example.com/"
    headers:
      Accept: application/json
      Content-Type: application/x-www-form-urlencoded
    body: |
      grant_type=authorization_code&code={{chains.authorization_code}}
  
  other: !request
    method: GET
    url: "http://www.example.com"
```

**Expected behavior**
The new line should not be included in the request body.

**Screenshots**
_If applicable, add screenshots to help explain your problem_

**Version (please complete the following information):**

- OS: Windows
- Terminal: Windows Terminal
- Slumber Version: 1.3.0

**Additional context**
