### ISSUE TITLE
Cannot catch nested token

### ISSUE THREAD

**Issue by AuroraLantean** [LucasPickering/slumber#247]
**Describe the bug**
```
  auth_token:
    source: !request
      recipe: get_token
    selector: $.data.token
    #selector: $['data']['token']
```
Cannot catch the token inside the response under `data`
```
{
  "data": {
    "token": "eyJ0eX.vbsgsdg.ddsfd"
  },
  "success": true
}
```
**To Reproduce**
_Steps to reproduce the behavior_

1. Clone my repo: `git clone git@github.com:AuroraLantean/axum-jwt.git`

**Expected behavior**
Compile and run the Axum server:
```
cargo run --bin axum-auth
```

Install Slumber:
https://slumber.lucaspickering.me/

See the slumber.yml file in the root directory...

Run Slumber commands:
`$ slumber` then use the UI to run APIs
OR
```
$ slumber request -p local public_view | jq

$ slumber request -p local get_token | jq
{
  "data": {
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImpvaG5kb2VAZ21haWwuY29tIiwiZXhwIjoxNzE3MTc0MTg5fQ.CmJoHeHBT_fi-VMBgoVjaXEN_dV1CNlxHSbP7X9md2Y"
  },
  "success": true
}

$ slumber request -p local secret_view | jq
{
  "data": {
    "message": "No token provided"
  },
  "success": false
}
```
**Screenshots**

**Version (please complete the following information):**

- OS: LinuxMint  21.3 Virginia, based on: Ubuntu 22.04 jammy
- Terminal: Zsh
- Slumber Version:  slumber 1.3.2

**Comment by AuroraLantean** [comment]
My bad... I made a mistake using Slumber... 

Docs: https://slumber.lucaspickering.me/book/api/request_collection/authentication.html
For Jwt tokens, I would really suggest you put an example in your doc like:
```
  #slumber request -p local secret_view | jq
  secret_view: !request
    method: GET
    url: "{{host}}/secret-view"
    authentication:
      !bearer "{{chains.auth_token}}"
```
