### ISSUE TITLE
Share configuration between collections

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#290]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**
Yes :)

**Is your feature request related to a problem? Please describe.**
_A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]_

It should be possible to import elements of a collection from one file to another. For example, if you use the same authentication process for several microservices, and each service has its own `slumber.yml` file, it would be nice to reuse the chain/request that provides authentication across all collections, so you only have to write it once.

**Describe the solution you'd like**
_A clear and concise description of what you want to happen_

A potential solution would be to support JSONRef is some parts of the collection. For example:

```
#common.yml
chains:
  username:
    source: !command
      command: [whoami]
    trim: both
  password:
    source: !prompt
      message: Password
    sensitive: true
  auth_token:
    source: !request
      recipe: login
      trigger: !expire 12h
    selector: $.form

requests:
  login: !request
    method: POST
    url: "{{host}}/anything/login"
    headers:
      Accept: application/json
    body: !form_urlencoded
      username: "{{username}}"
      password: "{{chains.password}}"
```

```
#slumber.yml
chains:
  auth_token: !reference common.yml#/chains/auth_token

requests:
  get_users: !request
    name: Get Users
    method: GET
    url: "{{host}}/get"
    authentication: !bearer "{{chains.auth_token}}"
```

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered_

- Inheritance, where a file can declare `extends: common.yml` and transparently use everything from it
  - Might be more magical and complicated to implement

**Additional context**
_Add any other context or screenshots about the feature request here_

**Comment by anussel5559** [comment]
@LucasPickering Is this a feature you'd still like to get added? I would love to look in to implementing this next (after I wrap up the ChainSource::Select stuff!).

When I initially started using slumber for testing my work's APIs this was one of the first "ah, bummer" things I hit (we use a micro-service architecture with shared auth - as you noted would be one of the biggest advantages of such a feature).

**Comment by LucasPickering** [comment]
@anussel5559 Yes definitely, but this is a very significant feature. The first step is figuring out a design for this. Do you have any thoughts on how you would want it to work?

**Comment by anussel5559** [comment]
yea! happy to brainstorm here.

Some of the complication/intricacies I see are:
- resource ids have to be globally unique
- a `Collection` is a stand-alone concept, having it's own resources. These map 1:1 to a config file, and the rest of the app has no concept of multiple collections.
- probably other things?

I think the easiest approach for users to grok might be one where they can build a `inherits from` concept, with a `extends` keyword or similar.

One approach for dealing with the id concerns is making the shape of the `extends` resource an object containing a relative file path and an assigned id - when we parse the extended collection, the resource ids in that extended collection are then prefixed with the assigned collection id thereby creating globally unique resource ids.

This allows the user to intuit how to reference a resource across collections. We can additionally panic/quit parsing if we detect any collection with a duplicate id as part of the Collection hierarchy.

This might look like this:
```yaml
--- base.yaml
profiles:  
  works:
    name: This Works
    data:
      host: https://httpbin.org
      username: xX{{chains.username}}Xx
      user_guid: abc123
chains:
  username:
    source: !command
      command: [whoami]
    trim: both

--- service1.yaml
extends: 
  - file: 'base.yaml' # relative filepath
    id: base
profiles:
  works:
    name: This Works
    data:
      host: https://httpbin.org
      username: xX{{base.chains.username}}Xx
      user_guid: abc123
chains:
  password:
    source: !prompt
      message: Password
    sensitive: true
requests:
  login: !request
    method: POST
    url: "{{host}}/anything/login"
    authentication: !basic
      username: "{{username}}"
      password: "{{chains.password}}"
```
The link is explicit in the target collection, and the collection can extend multiple additional collection.
Implementing might look like:

There's still some hand-waving to think through here, but hopefully this is a thread to start pulling on?

**Comment by LucasPickering** [comment]
@anussel5559 This is a good start. My first thought is that you use the words "extends" and "inheritance" but this feels more like "import" and "composition" to me. You're declaring an external resource (the "extended" collection) and assigning it an alias, then reference that alias selectively to import data from the external resource. To be clear, I prefer this approach over "true" inheritance (where everything from the parent is implicitly brought in), just want to be clear on terminology. I used an inheritance structure for a previous project [env-select](https://github.com/LucasPickering/env-select), and it worked alright there but it opens up a rats nest of both behavior and implementation issues (e.g. how deep do you go when merging data? do arrays concat or overwrite? etc).

With your design, I'm curious how you would reference things other than chains from the imported file. E.g. if you wanted `login` to be a common recipe in `base.yaml`, could you bring the entire recipe into `service1.yaml` with a single import statement?

This feels functionally similar to the option I've been leaning toward of using URIs to reference objects between . I would take a look at the [openapiv3](https://docs.rs/openapiv3/latest/openapiv3/) crate. The [OpenAPI spec makes heavy use of this pattern](https://swagger.io/specification/), allowing you to easily reference complex objects within a file or between files. (Note: In my original post I called this JSONRef but after doing more research I'm not sure if that's exactly what OpenAPI uses. It looks like JSONRef is an extension of JSONSchema, and Slumber collections certainly aren't JSONSchema compliant). 

The key to this in `openapiv3`'s API is the [ReferenceOr](https://docs.rs/openapiv3/latest/openapiv3/enum.ReferenceOr.html) type. With an equivalent in Slumber, any field that we want to be a referencable we would just wrap in `ReferenceOr`. For example, the `Recipe` struct might look like:
```
pub struct Recipe {
    #[serde(skip)] // This will be auto-populated from the map key
    pub id: RecipeId,
    pub name: Option<String>,
    pub method: Method,
    pub url: ReferenceOr<Template>,
    pub body: Option<ReferenceOr<RecipeBody>>,
    pub authentication: Option<ReferenceOr<Authentication>>,
    pub query: ReferenceOr<Vec<(String, Template)>>,
    pub headers: ReferenceOr<IndexMap<String, Template>>,
}
```

There are certainly some design decisions to be made around what should/shouldn't be referenceable, but that's the general idea.

## Example

This is an extension of the example in the original post, to show some more use cases:

```yaml
#common.yml
chains:
  username:
    source: !command
      command: [whoami]
    trim: both
  password:
    source: !prompt
      message: Password
    sensitive: true
  auth_token:
    source: !request
      recipe: login
      trigger: !expire 12h
    selector: $.form

requests:
  login: !request
    method: POST
    url: "{{host}}/anything/login"
    headers:
      Accept: application/json
    body: !form_urlencoded
      username: "{{username}}"
      password: "{{chains.password}}"

  get_current_user: !request
    method: POST
    url: "{{host}}/users/current"
    headers: !reference #/recipes/login/headers
    authentication: !bearer "{{chains.auth_token}}"
```

```yaml
#service.yml
chains:
  auth_token: !reference common.yml#/chains/auth_token

requests:
  get_current_user: !reference common.yaml#/recipes/get_current_user

  get_users: !request
    name: Get Users
    method: GET
    url: "{{host}}/get"
    authentication: !bearer "{{chains.auth_token}}"
```

## Pros

- Explicit
- Uses existing standards (URIs) and patterns (from OpenAPI)
- Powerful

## Cons

- Implementation is complex
- We need to explicitly declare what can be referenceable
- Complicates and slows down collection loads

## Implementation

The implementation for this I think would look something like:
- Create `ReferenceOr` type and stick it in various places throughout the collection definition
- Implementation deserialization for `ReferenceOr`, which would involve URI parsing
  - In the past I had checked if the `url` crate would work for this, but iirc that's specifically only for web URLs so it doesn't support URIs where the root is a file path (or no root at all, for same-file references)
- Add a post-deserialize step to the collection that resolves all references
  - This would be fallible, in case any references are invalid
  - We have a [minimal version of this in the openapi importer](https://github.com/LucasPickering/slumber/blob/master/crates/slumber_core/src/collection/openapi/resolve.rs) already. It'd be great to share code with that but realistically probably wouldn't work because the reference types are different.

We would also need to figure out how to make this as transparent as possible in the rest of the app. After loading and resolving, references should be transparent to any code that uses the collection. 

That's a lot of words. Thoughts?
