### ISSUE TITLE
Scoped unique IDs

### ISSUE THREAD

**Issue by unexist** [LucasPickering/slumber#293]
Currently it is not possible to re-use IDs even when used underneath different folders, this usually results in following message:

`Duplicate recipe/folder ID `get`; recipe/folder IDs must be globally unique`

Would it be feasible to limit that to the same scope/level, e.g. by using the name of the folder as a prefix?

For example:

```
requests:
  rest-a: !folder
    name: REST
    requests:
      get: !request
        method: GET
        url: "{{rest_a_url}}"

  rest-b: !folder
    name: REST
    requests:
      get: !request
        method: GET
        url: "{{rest_b_url}}"
```
        
So in this case the ID of the first get request becomes _rest-a-get_ and the second _rest-b-get_ respectively.
