### ISSUE TITLE
Add `command` source fo chains

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#31]
```yaml
chains:
  id: command
  source: !command echo hello
```

This would be useful for grabbing external values that aren't in files or env variables, e.g. current kube context
