### ISSUE TITLE
Support `trigger` on other ChainSource types

### ISSUE THREAD

**Issue by anussel5559** [LucasPickering/slumber#348]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?** yup!

**Is your feature request related to a problem? Please describe.**
Nope, just a limitation

**Describe the solution you'd like**
Currently, a `request` ChainSource has the ability to only trigger on certain conditions (expiration, everytime, only on first, etc...) but no other chain source supports that `trigger` configuration. I can think of a number of scenarios where it'd be really handy to only trigger other ChainSource types on specific conditions.

A concrete example: I've built a dependency chain that uses a `prompt` ChainSource to allow the user to pick a specific resource from the response of a different chain. using the id of THAT resource can drive further requests (essentially this API has a resource hierarchy). Currently making the subsequent requests requires that I choose the resource to drive the lower requests. It'd be nice to have the `trigger` condition available on this `prompt` ChainSource

**Describe alternatives you've considered**
There aren't really any - just have to deal with the prompt every request

**Additional context**
None

**Comment by LucasPickering** [comment]
I considered this when originally implementing request triggers ([option 3 in the initial issue](https://github.com/LucasPickering/slumber/issues/140)). I decided against it for a few reasons:
- Implementation complexity. It requires adding a cache for non-request chain values. Requests/responses have a specific schema in the internal SQLite DB where they're persisted, and prompts/files/etc. would need a separate store.
- UX inconsistency. For requests, the default value for `trigger` is `never`, meaning it won't automatically make requests unless you opt into that. This is pretty intuitive. For non-request chains though, you would intuitively expect the default to be `always` (and that's effectively what it is now). E.g. if you chain a prompt, you would expect the prompt to run every time, unless you opt out. It's totally possible to set the default value for `trigger` dynamically based on the chain variant, but it adds cognitive complexity for the user and is harder to implement.

I appreciate the friction of the current workflow and the usefulness of caching/triggers, but I'm still not convinced the added complexity is worth in. In many scenarios you can mitigate the annoyance of prompts using the `default` field. For example, if you have an endpoint `POST /groups` that creates a user group, then `POST /users` that creates a user and adds it to that group:

```yaml
chains:
  response_group_id:
    source: !request
      recipe: create_group
    selector: $.id
  
  group_id:
    source: !prompt
      default: "{{chains.response_group_id}}"

requests:
  create_group: !request
    method: POST
    url: "{{host}}/groups"
    body: !json
      name: "My Users"

  create_user: !request
    method: POST
    url: "{{host}}/users"
    body: !json
      name: "User 1"
      group: "{{chains.group_id}}"
```

You can create the group once, and from then on any time you create a user, it will prompt for a group ID with the ID of the created group populated by default. If that's that value you want to use most commonly, all you have to do is hit enter.

I know this isn't an equivalent solution, but hopefully it's helpful for you. If you share some more specifics about your request collection I might be able to give you some better suggestions about how to optimize it.
