### ISSUE TITLE
Profile/recipe inheritance

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#36]
Inheritance would be easier to use and more flexible than YAML anchors. Example:

```yaml
base: &base
  headers:
    Accept: application/json

requests:
  - <<: *base
    id: get
    method: GET
    url: "{{host}}/get"
    headers:
      Authorization: username:password
```

^^ this example does **not** work, because the `headers` in the child overrides the parent, and the `Accept` header is lost. An example with built-in inheritance would be:

```yaml
requests:
  - id: base
    hidden: true
    headers:
      Accept: application/json
  - id: get
    extends: base
    method: GET
    url: "{{host}}/get"
    headers:
      Authorization: username:password
```

We'd have to decide if we want to support multiple inheritance, and would also need to handle cycles so it would add the need for a validation step to collection parsing, which is annoying. Not sure how else to accomplish this though.
