### ISSUE TITLE
Support passing path parameters in TUI mode

### ISSUE THREAD

**Issue by quantonganh** [LucasPickering/slumber#392]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**

Yes.

**Is your feature request related to a problem? Please describe.**

Given the following recipe:

```
  instances: !folder
    requests:
      get_instance: !request
        method: GET
        url: "{{host}}/api/v1/instances/{{instance_id}}"
        authentication: !bearer "{{chains.token}}"
```

In CLI mode, we can pass the path parameters like this:

```
$ slumber request -p testing -o instance_id=1 get_instance
```

It would be useful to have the same functionality available in the TUI mode.

**Describe the solution you'd like**

Please add a tab for path parameters (or combine it with query parameters) and allow editing using `e` key.

Thank you!

**Comment by LucasPickering** [comment]
Currently you can accomplish this using a [prompt chain](https://slumber.lucaspickering.me/book/api/request_collection/chain_source.html#prompt), which would look like:

```yaml
chains:
  instance_id:
    source: !prompt

requests:
  instances: !folder
    requests:
      get_instance: !request
        method: GET
        url: "{{host}}/api/v1/instances/{{chains.instance_id}}"
        authentication: !bearer "{{chains.token}}"
```

This will prompt you on every request to enter an instance ID, which may or may not be what you want. You can provide a `default` field to the prompt to make it easier (and that value can be a template itself, if you want the default to be dynamic).

Making "path parameters" dynamic is a large change because currently Slumber has no concept of path parameters: the URL is just a string. Adding this would add a lot of complexity. What would be much easier though and fit better into the current behavior though would be to just make the entire URL editable.
