### ISSUE TITLE
Support parse JSON format with keys containing special characters

### ISSUE THREAD

**Issue by RanlyX** [LucasPickering/slumber#393]
Hi,
I would like to perform dynamic selection, querying again based on a path from the response of a previous request.
But response json key not common pattern. Slumber occurs error:
```
Error loading data from "/home/ranly/projects/s1f/apis/abmc.yml"
└─at position 13, in dot member name, must start with lowercase alpha or '_'
```
Get reponse body of accounts request:
```
{
  "@odata.context": "/redfish/v1/$metadata#ManagerAccountCollection.ManagerAccountCollection",
  "@odata.etag": "\"1643076270\"",
  "@odata.id": "/redfish/v1/AccountService/Accounts",
  "@odata.type": "#ManagerAccountCollection.ManagerAccountCollection",
  "Description": "Collection for Manager Accounts",
  "Members": [
    {
      "@odata.id": "/redfish/v1/AccountService/Accounts/1"
    },
    {
      "@odata.id": "/redfish/v1/AccountService/Accounts/2"
    },
    {
      "@odata.id": "/redfish/v1/AccountService/Accounts/3"
    }
  ],
  "Members@odata.count": 3,
  "Name": "Accounts Collection"
}
```

The chains of my collection:
```
chains:
  account_id:
    source: !select
      message: Select a account
      options: "{{chains.account_list}}"
  account_list:
    source: !request
      recipe: get_account_collection
    selector: $.Members[*]."@odata.id"
    selector_mode: array
```

Has this feature already been implemented, or is it actually an issue?
It seems that I couldn't find any explanation of the valid parsing method in the documentation.
Thank you
