### ISSUE TITLE
Select JWT Bearer Token from response Header, then use it in request Header

### ISSUE THREAD

**Issue by AuroraLantean** [LucasPickering/slumber#463]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**
yes
I found those closed issues:
- Allow header values to be selected from selector: https://github.com/LucasPickering/slumber/issues/184
- Cannot catch nested JWT Web Token: https://github.com/LucasPickering/slumber/issues/247

**Describe the bug**
I can get the the whole `authorization` header value as `Bearer my_token` from my Login response header, but to use it, I have to use this syntax
```
authentication: !bearer "{{chains.auth_token_in_header}}"
```
, which adds "Bearer " again

Docs:
- Bear Token in Authorization: https://slumber.lucaspickering.me/book/api/request_collection/authentication.html

- Chain Request Section: https://slumber.lucaspickering.me/book/api/request_collection/chain_source.html#chain-request-section

**To Reproduce**
```
chains:
  auth_token_in_header:
    source: !request
      recipe: login
      section: !header Authorization

requests:
  get_authorized_items: !request
    method: GET
    url: "{{host}}/authorized_items"
    authentication: !bearer "{{chains.auth_token_in_header}}"
```

**Expected behavior**
the `authorization` header value should be `Bearer my_token`

**Screenshots**
![Image](https://github.com/user-attachments/assets/be0b54cf-6b7b-48eb-bcd6-e57cb23a5a64)

**Version (please complete the following information):**
    OS: Linux Mint 22.1 Xia based on Ubuntu 24.04 noble
    Terminal: Zsh
    Slumber Version: slumber 2.5.0

**Additional context**

**Comment by LucasPickering** [comment]
@AuroraLantean You can set the `Authorization` header directly rather than using the `authorization` shortcut, to skip the added `Bearer` prefix.

```yaml
chains:
  auth_token_in_header:
    source: !request
      recipe: login
      section: !header Authorization

requests:
  get_authorized_items: !request
    method: GET
    url: "{{host}}/authorized_items"
    headers:
      Authorization: "{{chains.auth_token_in_header}}"
```
