### ISSUE TITLE
Option to prompt the user if selector JSONPath points to an array

### ISSUE THREAD

**Issue by pirafrank** [LucasPickering/slumber#478]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**

Yes

**Is your feature request related to a problem? Please describe.**
Consider a use case of two REST APIs, `/tags` and `/tags/{{tag_id}}`. To make it easy, let's suppose the /tags API returns an array of strings.
Right now I can make `tag_id` a parameter using a chain and getting the value from the /tags API response via a `selector`. Yet I can only get a fixed element as I have to specify the index in the JSONPath. `selector_mode: single` doesn't allow to choose an element from the array.

![Image](https://github.com/user-attachments/assets/a53def98-c808-4753-9e9d-f897b5e51de7)

**Describe the solution you'd like**
I'd like the possibility for the user to be prompted to choose a value if the JSONPath specified the selector points to an array (e.g. `$[*].name`). In the example above, the array values would be fetched from the /tags API linked recipe. If `selector_mode: single`, the app would prompt the user to choose a value.

Alternatively, a new `selector_mode: prompt` would handle such cases, prompting the user to choose a value from a list if the JSONPath specified the selector points to an array (e.g. `$[*].name`).

**Describe alternatives you've considered**
I considered put all possible values in an external txt file. This solution while it represents a temporary workaround, is not viable for dynamic responses, as you need to script externally the update of the txt file.

**Additional context**
I looked there and there are no viable alternatives. [here
](https://slumber.lucaspickering.me/book/api/request_collection/chain.html?highlight=selector#selector-mode)

Thank you!

**Comment by LucasPickering** [comment]
You can accomplish this by combining a `request` chain with a `select` chain. This should do what you want:

```yaml
chains:
  tag:
    source: !select
      message: Select a tag
      options: "{{chains.tags}}"
  tags:
    source: !request
      recipe: list_tags
    selector: $.json.tags[*]
    selector_mode: array

requests:
  list_tags: !request
    method: POST
    url: https://httpbin.org/anything/tags
    body: !json { "tags": ["tag1", "tag2", "tag3"] }
  get_tag: !request
    method: GET
    url: https://httpbin.org/anything/tags/{{chains.tag}}
```

Note: In my example, `list_tags` is a `POST` request just so I could submit a body with an array in it.

There's an example of this [in the docs](https://slumber.lucaspickering.me/book/api/request_collection/chain_source.html#examples-6), although it's probably not easy to find if you don't already know what you're looking for. What do you think I could change in the docs to make this more discoverable?
