### ISSUE TITLE
Support prompt input number

### ISSUE THREAD

**Issue by funme** [LucasPickering/slumber#494]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**
Yes

**Is your feature request related to a problem? Please describe.**
```yml
profiles:
  prd:
    name: Production
    data:
      host: https://httpbin.org

chains:
  number_int:
    source: !prompt
      message: input int

.ignore:
  base: &base
    headers:
      Accept: application/json

requests:
  create: !request
    <<: *base
    method: POST
    url: "{{host}}/anything"
    body:
      !json {
        "tag": "test",
        "number": "{{chains.number_int}}"
      }
```

**Describe the solution you'd like**
now input 888 then output json

```json
{
  "tag":"test",
  "number": "888"
}
```

expect

```json
{
  "tag":"test",
  "number": 888
}
```

1. tried with sed 's/"//g'，but failed
2. tried with jq -r, success remove the end ", but the prefix " still there，failed too

**Describe alternatives you've considered**

**Additional context**

**Comment by LucasPickering** [comment]
You can build the JSON yourself as a string rather than using the `!json` tag for this, then you can drop the quotes around the template.

```yaml
requests:
  create: !request
    <<: *base
    method: POST
    url: "{{host}}/anything"
    body: >
      { "tag": "test", "number": {{chains.number_int}} }
```

Make sure to set the `Content-Type: application/json` header manually, since that will no longer be automatic without the `!json` tag.

I know it's tedious but this is the best solution at the moment. I'm working on a large scale refactor of the entire config system that will improve this, but that's a few months away at the earliest.
